import { CATEGORY_CONFIG, DEFAULT_CATEGORY_SLUG, PRODUCTS_PER_PAGE, type CategorySlug } from './constants.ts'
import {
  categoryNavItemSchema,
  type CategoryNavItem,
  type Product,
  productSchema,
  productSearchParamsSchema,
  type ProductSearchParams,
  type Review,
} from './schemas.ts'

type ProductSeed = {
  slug: string
  name: string
  subCategory: string
  benefit: string
  description: string
  shortDescription: string
  price: number
  badge: string
  ingredients: string[]
  usage: string
  unit: string
  manufacturer: string
  countryOfOrigin: string
  form: string
  specification: string
  shelfLife: string
  ingredientHighlight: string
  imageLabels?: string[]
  rating?: number
  reviewCount?: number
  commentCount?: number
}

type CategoryMeta = CategoryNavItem & {
  prefix: string
}

const categoryMetaMap: Record<CategorySlug, CategoryMeta> = {
  'thuc-pham-chuc-nang': { ...CATEGORY_CONFIG[0], prefix: 'TPCN' },
  'cham-soc-da': { ...CATEGORY_CONFIG[1], prefix: 'CSD' },
  'thiet-bi-y-te': { ...CATEGORY_CONFIG[2], prefix: 'TBYT' },
  thuoc: { ...CATEGORY_CONFIG[3], prefix: 'THUOC' },
}

function createReviews(name: string): Review[] {
  return [
    {
      author: 'Ngọc Anh',
      rating: 5,
      date: '08/06/2026',
      title: 'Dùng đều thấy ổn',
      content: `${name} đóng gói chắc chắn, giao nhanh và dễ dùng trong sinh hoạt hằng ngày.`,
    },
    {
      author: 'Minh Khang',
      rating: 4,
      date: '03/06/2026',
      title: 'Thông tin rõ ràng',
      content:
        'Trang chi tiết ghi đủ thành phần, cách dùng và quy cách nên dễ cân nhắc trước khi mua.',
    },
    {
      author: 'Thanh Vy',
      rating: 5,
      date: '28/05/2026',
      title: 'Phù hợp với nhu cầu',
      content: 'Mình tìm được đúng nhóm sản phẩm đang cần và phần mô tả khá dễ đọc.',
    },
  ]
}

function createProduct(category: CategoryMeta, seed: ProductSeed, index: number): Product {
  return productSchema.parse({
    slug: seed.slug,
    name: seed.name,
    topCategory: category.label,
    topCategorySlug: category.slug,
    subCategory: seed.subCategory,
    benefit: seed.benefit,
    description: seed.description,
    shortDescription: seed.shortDescription,
    price: seed.price,
    badge: seed.badge,
    ingredients: seed.ingredients,
    usage: seed.usage,
    unit: seed.unit,
    defaultQuantity: 1,
    sku: `${category.prefix}-${String(index + 1).padStart(3, '0')}`,
    rating: seed.rating ?? 4.8,
    reviewCount: seed.reviewCount ?? 10,
    commentCount: seed.commentCount ?? 18,
    officialName: `${seed.name} - ${category.label}`,
    registrationNumber: `${7350 + index}/${new Date().getFullYear()}/DKSP`,
    form: seed.form,
    specification: seed.specification,
    manufacturer: seed.manufacturer,
    countryOfOrigin: seed.countryOfOrigin,
    shelfLife: seed.shelfLife,
    ingredientHighlight: seed.ingredientHighlight,
    images:
      seed.imageLabels ?? ['Ảnh chính', 'Mặt trước', 'Mặt bên', 'Thành phần', 'Hướng dẫn sử dụng'],
    reviews: createReviews(seed.name),
  })
}

function buildProducts(categorySlug: CategorySlug, seeds: ProductSeed[]) {
  return seeds.map((seed, index) => createProduct(categoryMetaMap[categorySlug], seed, index))
}

const supplementProducts = buildProducts('thuc-pham-chuc-nang', [
  {
    slug: 'omega-3-premium',
    name: 'Omega-3 Premium',
    subCategory: 'Tim mạch',
    benefit: 'Hỗ trợ tim mạch và não bộ',
    description: 'Dầu cá tinh khiết giàu EPA và DHA cho người cần chăm sóc tim mạch mỗi ngày.',
    shortDescription: 'Bổ sung Omega-3 giúp hỗ trợ tim mạch, mắt và khả năng tập trung.',
    price: 389000,
    badge: 'Bán chạy',
    ingredients: ['EPA 360mg', 'DHA 240mg', 'Dầu cá tinh khiết 1000mg'],
    usage: 'Uống 1 viên, ngày 2 lần sau bữa ăn.',
    unit: 'Hộp',
    manufacturer: 'Nordic Pure Labs',
    countryOfOrigin: 'Na Uy',
    form: 'Viên nang mềm',
    specification: 'Hộp 60 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa EPA 360mg, DHA 240mg.',
  },
  {
    slug: 'vitamin-c-1000mg',
    name: 'Vitamin C 1000mg',
    subCategory: 'Đề kháng',
    benefit: 'Tăng cường đề kháng hằng ngày',
    description: 'Vitamin C hàm lượng cao kết hợp bioflavonoid hỗ trợ miễn dịch và chống oxy hóa.',
    shortDescription: 'Bổ sung vitamin C cho người cần nâng đỡ hệ miễn dịch và giảm mệt mỏi.',
    price: 219000,
    badge: 'Mới',
    ingredients: ['Vitamin C 1000mg', 'Citrus bioflavonoids 50mg'],
    usage: 'Uống 1 viên mỗi ngày sau bữa sáng.',
    unit: 'Hộp',
    manufacturer: 'Healthy Plus',
    countryOfOrigin: 'Úc',
    form: 'Viên nén',
    specification: 'Hộp 30 viên',
    shelfLife: '36 tháng',
    ingredientHighlight: 'Mỗi viên chứa Vitamin C 1000mg và bioflavonoid.',
  },
  {
    slug: 'collagen-peptide',
    name: 'Collagen Peptide',
    subCategory: 'Làm đẹp',
    benefit: 'Hỗ trợ da, tóc và móng',
    description: 'Collagen peptide thủy phân kết hợp biotin và kẽm cho nhu cầu làm đẹp từ bên trong.',
    shortDescription: 'Dòng collagen dạng bột cho nhu cầu chăm sóc sắc đẹp và nuôi dưỡng làn da.',
    price: 559000,
    badge: 'Ưu đãi',
    ingredients: ['Marine collagen peptides 5000mg', 'Biotin 2500mcg', 'Zinc 7mg'],
    usage: 'Pha 1 muỗng với 200ml nước, dùng 1 lần mỗi ngày.',
    unit: 'Hộp',
    manufacturer: 'Beauty Nutrition Co.',
    countryOfOrigin: 'Nhật Bản',
    form: 'Bột hòa tan',
    specification: 'Hộp 15 gói',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi khẩu phần chứa Collagen peptide 5000mg.',
  },
  {
    slug: 'glucosamine-joint-care',
    name: 'Glucosamine Joint Care',
    subCategory: 'Xương khớp',
    benefit: 'Hỗ trợ vận động linh hoạt',
    description: 'Kết hợp glucosamine, chondroitin và MSM để bổ sung dưỡng chất cho sụn khớp.',
    shortDescription: 'Công thức hỗ trợ xương khớp cho người cần duy trì vận động hằng ngày.',
    price: 465000,
    badge: 'Nổi bật',
    ingredients: ['Glucosamine 1500mg', 'Chondroitin 200mg', 'MSM 150mg'],
    usage: 'Uống 2 viên mỗi ngày sau bữa trưa.',
    unit: 'Hộp',
    manufacturer: 'MoveWell Labs',
    countryOfOrigin: 'Hoa Kỳ',
    form: 'Viên nén bao phim',
    specification: 'Hộp 90 viên',
    shelfLife: '36 tháng',
    ingredientHighlight: 'Mỗi 2 viên chứa Glucosamine 1500mg.',
  },
  {
    slug: 'probiotic-balance',
    name: 'Probiotic Balance',
    subCategory: 'Tiêu hóa',
    benefit: 'Cân bằng hệ vi sinh đường ruột',
    description: 'Bổ sung lợi khuẩn và chất xơ hòa tan cho người thường xuyên đầy bụng, khó tiêu.',
    shortDescription: 'Dòng lợi khuẩn dùng hằng ngày cho người có nhu cầu chăm sóc tiêu hóa.',
    price: 298000,
    badge: 'Bán chạy',
    ingredients: ['Lactobacillus 10B CFU', 'Inulin 500mg'],
    usage: 'Uống 1 viên sau bữa tối.',
    unit: 'Hộp',
    manufacturer: 'BioDigest',
    countryOfOrigin: 'Hàn Quốc',
    form: 'Viên nang cứng',
    specification: 'Hộp 30 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa 10 tỷ lợi khuẩn và Inulin.',
  },
  {
    slug: 'calcium-d3-k2',
    name: 'Calcium D3 K2',
    subCategory: 'Xương khớp',
    benefit: 'Hỗ trợ xương chắc khỏe',
    description: 'Canxi hữu cơ kết hợp vitamin D3 và K2 giúp tăng khả năng hấp thu và định hướng canxi.',
    shortDescription: 'Bổ sung canxi cho người cần hỗ trợ xương khớp và mật độ xương.',
    price: 325000,
    badge: 'Mới',
    ingredients: ['Calcium 600mg', 'Vitamin D3 1000IU', 'Vitamin K2 45mcg'],
    usage: 'Uống 2 viên mỗi ngày sau bữa ăn.',
    unit: 'Hộp',
    manufacturer: 'BoneCare Nutrition',
    countryOfOrigin: 'Đức',
    form: 'Viên nén',
    specification: 'Hộp 60 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi 2 viên chứa Canxi 600mg và Vitamin D3 1000IU.',
  },
  {
    slug: 'milk-thistle-liver',
    name: 'Milk Thistle Liver Support',
    subCategory: 'Gan mật',
    benefit: 'Hỗ trợ chức năng gan',
    description: 'Chiết xuất kế sữa kết hợp atiso và nghệ cho người cần chăm sóc chức năng gan.',
    shortDescription: 'Lựa chọn phổ biến cho người cần hỗ trợ chức năng gan và tiêu hóa dầu mỡ.',
    price: 279000,
    badge: 'Phổ biến',
    ingredients: ['Milk thistle 300mg', 'Artichoke 100mg', 'Turmeric extract 50mg'],
    usage: 'Uống 1 viên, ngày 2 lần.',
    unit: 'Hộp',
    manufacturer: 'Herbal Support',
    countryOfOrigin: 'Việt Nam',
    form: 'Viên nang',
    specification: 'Hộp 30 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa kế sữa 300mg và atiso 100mg.',
  },
  {
    slug: 'magnesium-sleep',
    name: 'Magnesium Sleep Support',
    subCategory: 'Ngủ ngon',
    benefit: 'Thư giãn cơ thể và hỗ trợ giấc ngủ',
    description: 'Magnesium kết hợp vitamin B6 hỗ trợ thư giãn thần kinh và cải thiện chất lượng ngủ.',
    shortDescription: 'Hỗ trợ giấc ngủ cho người làm việc căng thẳng và ngủ chưa sâu.',
    price: 249000,
    badge: 'Dễ chọn',
    ingredients: ['Magnesium glycinate 200mg', 'Vitamin B6 10mg'],
    usage: 'Uống 1 viên trước khi ngủ 30 phút.',
    unit: 'Hộp',
    manufacturer: 'Calm Rest',
    countryOfOrigin: 'Hoa Kỳ',
    form: 'Viên nang',
    specification: 'Hộp 30 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa Magnesium glycinate 200mg.',
  },
  {
    slug: 'zinc-plus',
    name: 'Zinc Plus',
    subCategory: 'Đề kháng',
    benefit: 'Hỗ trợ miễn dịch và làn da',
    description: 'Kẽm hữu cơ kết hợp vitamin B6, hữu ích cho sức đề kháng và quá trình phục hồi da.',
    shortDescription: 'Sản phẩm bổ sung kẽm hằng ngày cho nhu cầu miễn dịch và làm đẹp.',
    price: 179000,
    badge: 'Tiết kiệm',
    ingredients: ['Zinc 15mg', 'Vitamin B6 5mg'],
    usage: 'Uống 1 viên mỗi ngày sau bữa sáng.',
    unit: 'Hộp',
    manufacturer: 'Immuno Care',
    countryOfOrigin: 'Singapore',
    form: 'Viên nén',
    specification: 'Hộp 30 viên',
    shelfLife: '36 tháng',
    ingredientHighlight: 'Mỗi viên chứa Kẽm 15mg.',
  },
  {
    slug: 'multivitamin-family',
    name: 'Multivitamin Family',
    subCategory: 'Tổng hợp',
    benefit: 'Bổ sung vitamin và khoáng chất cơ bản',
    description: 'Viên uống tổng hợp cho người bận rộn cần duy trì thể lực mỗi ngày.',
    shortDescription: 'Multivitamin cơ bản cho gia đình và người có lịch sinh hoạt dày.',
    price: 339000,
    badge: 'Ưu tiên',
    ingredients: ['13 vitamins', '10 minerals'],
    usage: 'Uống 1 viên mỗi ngày sau bữa ăn.',
    unit: 'Hộp',
    manufacturer: 'Family Health Nutrition',
    countryOfOrigin: 'Úc',
    form: 'Viên nén',
    specification: 'Hộp 60 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Bổ sung 13 vitamin và 10 khoáng chất thiết yếu.',
  },
  {
    slug: 'coq10-heart-energy',
    name: 'CoQ10 Heart Energy',
    subCategory: 'Tim mạch',
    benefit: 'Hỗ trợ năng lượng tế bào',
    description: 'Coenzyme Q10 giúp duy trì sức bền tim mạch và hỗ trợ thể lực.',
    shortDescription: 'Bổ sung CoQ10 cho người cần duy trì vận động và sức bền.',
    price: 489000,
    badge: 'Cao cấp',
    ingredients: ['CoQ10 200mg', 'Vitamin E 20IU'],
    usage: 'Uống 1 viên mỗi ngày trong bữa ăn có chất béo.',
    unit: 'Hộp',
    manufacturer: 'Active Life Pharma',
    countryOfOrigin: 'Hoa Kỳ',
    form: 'Viên nang mềm',
    specification: 'Hộp 30 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa CoQ10 200mg.',
  },
  {
    slug: 'beauty-biotin',
    name: 'Beauty Biotin',
    subCategory: 'Làm đẹp',
    benefit: 'Hỗ trợ tóc chắc và móng khỏe',
    description: 'Biotin hàm lượng cao kết hợp kẽm và selenium cho nhu cầu chăm sóc tóc, móng.',
    shortDescription: 'Viên uống làm đẹp tập trung vào tóc, móng và độ bóng khỏe.',
    price: 205000,
    badge: 'Mới',
    ingredients: ['Biotin 5000mcg', 'Zinc 7mg', 'Selenium 40mcg'],
    usage: 'Uống 1 viên mỗi ngày sau bữa trưa.',
    unit: 'Hộp',
    manufacturer: 'Pure Beauty Lab',
    countryOfOrigin: 'Hàn Quốc',
    form: 'Viên nang',
    specification: 'Hộp 30 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa Biotin 5000mcg.',
  },
  {
    slug: 'omega-369',
    name: 'Omega 3-6-9',
    subCategory: 'Tim mạch',
    benefit: 'Bổ sung acid béo thiết yếu',
    description: 'Công thức tổng hợp omega 3, 6, 9 từ dầu cá và dầu hạt lanh, hỗ trợ tim mạch và làn da.',
    shortDescription: 'Bổ sung acid béo thiết yếu cho cơ thể và làn da khỏe hơn.',
    price: 315000,
    badge: 'Phổ biến',
    ingredients: ['Fish oil 600mg', 'Flaxseed oil 300mg', 'Borage oil 100mg'],
    usage: 'Uống 2 viên mỗi ngày sau bữa sáng.',
    unit: 'Hộp',
    manufacturer: 'Nature Balance',
    countryOfOrigin: 'Canada',
    form: 'Viên nang mềm',
    specification: 'Hộp 60 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Bổ sung Omega 3, 6, 9 từ dầu cá và hạt lanh.',
  },
  {
    slug: 'vitamin-d3-2000iu',
    name: 'Vitamin D3 2000IU',
    subCategory: 'Xương khớp',
    benefit: 'Hỗ trợ hấp thu canxi',
    description: 'Vitamin D3 phù hợp cho người ít tiếp xúc ánh nắng và cần chăm sóc xương khớp.',
    shortDescription: 'Bổ sung D3 hằng ngày cho người ít ra nắng và cần hỗ trợ xương.',
    price: 169000,
    badge: 'Tiết kiệm',
    ingredients: ['Vitamin D3 2000IU'],
    usage: 'Uống 1 viên mỗi ngày sau bữa sáng.',
    unit: 'Hộp',
    manufacturer: 'Sunlight Care',
    countryOfOrigin: 'Úc',
    form: 'Viên nang',
    specification: 'Hộp 30 viên',
    shelfLife: '36 tháng',
    ingredientHighlight: 'Mỗi viên chứa Vitamin D3 2000IU.',
  },
  {
    slug: 'iron-folate',
    name: 'Iron Folate',
    subCategory: 'Tổng hợp',
    benefit: 'Bổ sung sắt và acid folic',
    description: 'Phù hợp cho người cần hỗ trợ tạo máu và bổ sung vi chất trong giai đoạn đặc biệt.',
    shortDescription: 'Bổ sung sắt và folate cho nhu cầu dinh dưỡng chuyên biệt.',
    price: 189000,
    badge: 'Cần thiết',
    ingredients: ['Iron 27mg', 'Folic acid 400mcg', 'Vitamin B12 6mcg'],
    usage: 'Uống 1 viên mỗi ngày sau bữa tối.',
    unit: 'Hộp',
    manufacturer: 'Women Care Nutrition',
    countryOfOrigin: 'Pháp',
    form: 'Viên nang',
    specification: 'Hộp 30 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa Sắt 27mg và Acid folic 400mcg.',
  },
  {
    slug: 'digestive-enzymes',
    name: 'Digestive Enzymes',
    subCategory: 'Tiêu hóa',
    benefit: 'Hỗ trợ tiêu hóa và hấp thu',
    description: 'Tập hợp enzyme tiêu hóa giúp cơ thể xử lý tinh bột, đạm và chất béo tốt hơn.',
    shortDescription: 'Phù hợp cho người hay đầy bụng sau ăn và cần hỗ trợ tiêu hóa.',
    price: 259000,
    badge: 'Thuận tiện',
    ingredients: ['Amylase', 'Protease', 'Lipase'],
    usage: 'Uống 1 viên cùng bữa ăn chính.',
    unit: 'Hộp',
    manufacturer: 'Digestive Science',
    countryOfOrigin: 'Hoa Kỳ',
    form: 'Viên nang',
    specification: 'Hộp 30 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Bổ sung enzyme tiêu hóa cơ bản cho bữa ăn nhiều đạm và chất béo.',
  },
  {
    slug: 'lutein-eye-care',
    name: 'Lutein Eye Care',
    subCategory: 'Mắt',
    benefit: 'Hỗ trợ thị lực và giảm mỏi mắt',
    description: 'Lutein và zeaxanthin dành cho người làm việc nhiều với màn hình.',
    shortDescription: 'Dòng hỗ trợ mắt cho dân văn phòng và người dùng màn hình nhiều.',
    price: 349000,
    badge: 'Nổi bật',
    ingredients: ['Lutein 20mg', 'Zeaxanthin 4mg', 'Vitamin A'],
    usage: 'Uống 1 viên mỗi ngày sau bữa sáng.',
    unit: 'Hộp',
    manufacturer: 'Vision Health',
    countryOfOrigin: 'Mỹ',
    form: 'Viên nang mềm',
    specification: 'Hộp 30 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa Lutein 20mg và Zeaxanthin 4mg.',
  },
  {
    slug: 'ginkgo-memory',
    name: 'Ginkgo Memory',
    subCategory: 'Não bộ',
    benefit: 'Hỗ trợ tuần hoàn và trí nhớ',
    description: 'Chiết xuất bạch quả kết hợp vitamin nhóm B cho người cần tập trung tốt hơn.',
    shortDescription: 'Sản phẩm hỗ trợ não bộ và sự tỉnh táo trong công việc.',
    price: 299000,
    badge: 'Được chọn nhiều',
    ingredients: ['Ginkgo biloba extract 120mg', 'Vitamin B6', 'Vitamin B12'],
    usage: 'Uống 1 viên, ngày 2 lần sau bữa ăn.',
    unit: 'Hộp',
    manufacturer: 'MindWell',
    countryOfOrigin: 'Đức',
    form: 'Viên nén',
    specification: 'Hộp 60 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Chiết xuất bạch quả 120mg hỗ trợ tuần hoàn và tập trung.',
  },
  {
    slug: 'evening-primrose',
    name: 'Evening Primrose',
    subCategory: 'Nội tiết',
    benefit: 'Hỗ trợ cân bằng nội tiết',
    description: 'Dầu hoa anh thảo phù hợp cho nhu cầu chăm sóc nội tiết và làn da.',
    shortDescription: 'Lựa chọn phổ biến trong nhóm hỗ trợ nội tiết nữ.',
    price: 329000,
    badge: 'Phổ biến',
    ingredients: ['Evening primrose oil 1000mg', 'Vitamin E'],
    usage: 'Uống 1 viên, ngày 2 lần sau bữa ăn.',
    unit: 'Hộp',
    manufacturer: 'Women Harmony',
    countryOfOrigin: 'Úc',
    form: 'Viên nang mềm',
    specification: 'Hộp 60 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa dầu hoa anh thảo 1000mg.',
  },
  {
    slug: 'ashwagandha-balance',
    name: 'Ashwagandha Balance',
    subCategory: 'Giảm căng thẳng',
    benefit: 'Hỗ trợ cân bằng tinh thần',
    description: 'Chiết xuất ashwagandha dành cho người cần giảm áp lực và duy trì năng lượng.',
    shortDescription: 'Phù hợp cho người làm việc áp lực và cần tinh thần ổn định hơn.',
    price: 379000,
    badge: 'Xu hướng',
    ingredients: ['Ashwagandha extract 300mg'],
    usage: 'Uống 1 viên, ngày 2 lần.',
    unit: 'Hộp',
    manufacturer: 'Adaptogen Lab',
    countryOfOrigin: 'Ấn Độ',
    form: 'Viên nang',
    specification: 'Hộp 60 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa Ashwagandha extract 300mg.',
  },
  {
    slug: 'spirulina-green',
    name: 'Spirulina Green',
    subCategory: 'Tổng hợp',
    benefit: 'Bổ sung tảo xoắn giàu vi chất',
    description: 'Tảo xoắn giúp bổ sung dinh dưỡng cho người ăn uống thiếu cân bằng.',
    shortDescription: 'Thêm một lựa chọn dinh dưỡng xanh cho người bận rộn.',
    price: 229000,
    badge: 'Dễ dùng',
    ingredients: ['Spirulina powder 500mg'],
    usage: 'Uống 2 viên mỗi ngày sau bữa ăn.',
    unit: 'Hộp',
    manufacturer: 'Green Vital',
    countryOfOrigin: 'Nhật Bản',
    form: 'Viên nén',
    specification: 'Hộp 100 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Bổ sung tảo xoắn giàu vi chất thiết yếu.',
  },
  {
    slug: 'cranberry-urinary',
    name: 'Cranberry Urinary',
    subCategory: 'Tiết niệu',
    benefit: 'Hỗ trợ đường tiết niệu',
    description: 'Chiết xuất nam việt quất dành cho nhu cầu chăm sóc đường tiết niệu hằng ngày.',
    shortDescription: 'Phù hợp cho người cần hỗ trợ vùng tiết niệu và bổ sung chống oxy hóa.',
    price: 309000,
    badge: 'Được quan tâm',
    ingredients: ['Cranberry extract 400mg', 'Vitamin C 60mg'],
    usage: 'Uống 1 viên, ngày 2 lần với nước.',
    unit: 'Hộp',
    manufacturer: 'Urinary Care Labs',
    countryOfOrigin: 'Canada',
    form: 'Viên nang',
    specification: 'Hộp 30 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa chiết xuất nam việt quất 400mg.',
  },
  {
    slug: 'turmeric-curcumin',
    name: 'Turmeric Curcumin',
    subCategory: 'Gan mật',
    benefit: 'Hỗ trợ tiêu hóa và chống oxy hóa',
    description: 'Curcumin kết hợp tiêu đen giúp tăng khả năng hấp thu và hỗ trợ sức khỏe tổng thể.',
    shortDescription: 'Dòng nghệ curcumin cho nhu cầu tiêu hóa và chăm sóc cơ thể.',
    price: 289000,
    badge: 'Phổ biến',
    ingredients: ['Curcumin 500mg', 'Black pepper extract 5mg'],
    usage: 'Uống 1 viên, ngày 2 lần sau ăn.',
    unit: 'Hộp',
    manufacturer: 'Herbal Daily',
    countryOfOrigin: 'Việt Nam',
    form: 'Viên nang',
    specification: 'Hộp 60 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi viên chứa Curcumin 500mg.',
  },
  {
    slug: 'electrolyte-plus',
    name: 'Electrolyte Plus',
    subCategory: 'Năng lượng',
    benefit: 'Bù nước và điện giải',
    description: 'Viên sủi điện giải cho người vận động nhiều hoặc cần phục hồi nhanh sau đổ mồ hôi.',
    shortDescription: 'Giải pháp bù điện giải nhanh và tiện lợi.',
    price: 149000,
    badge: 'Tiện lợi',
    ingredients: ['Sodium', 'Potassium', 'Magnesium', 'Vitamin C'],
    usage: 'Hòa 1 viên với 300ml nước, dùng khi cần.',
    unit: 'Tuýp',
    manufacturer: 'Hydra Labs',
    countryOfOrigin: 'Đức',
    form: 'Viên sủi',
    specification: 'Tuýp 20 viên',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Bổ sung điện giải và vitamin C nhanh chóng.',
  },
  {
    slug: 'protein-shake-lean',
    name: 'Protein Shake Lean',
    subCategory: 'Thể lực',
    benefit: 'Bổ sung protein sau vận động',
    description: 'Dạng bột whey tiện dùng cho người cần bổ sung đạm và phục hồi cơ bắp.',
    shortDescription: 'Phù hợp cho người tập luyện hoặc cần tăng cường protein khẩu phần.',
    price: 599000,
    badge: 'Cao cấp',
    ingredients: ['Whey protein isolate 22g', 'BCAA'],
    usage: 'Pha 1 muỗng với 250ml nước, dùng sau tập hoặc giữa bữa.',
    unit: 'Hộp',
    manufacturer: 'Fit Nutrition',
    countryOfOrigin: 'Hoa Kỳ',
    form: 'Bột',
    specification: 'Hộp 900g',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Mỗi khẩu phần cung cấp 22g whey protein isolate.',
  },
])

const skincareProducts = buildProducts('cham-soc-da', [
  {
    slug: 'gentle-cleanser-b5',
    name: 'Sữa rửa mặt Gentle Cleanser B5',
    subCategory: 'Làm sạch',
    benefit: 'Làm sạch dịu nhẹ, không khô da',
    description: 'Sữa rửa mặt dịu nhẹ với B5 và glycerin phù hợp da nhạy cảm.',
    shortDescription: 'Làm sạch cơ bản cho da nhạy cảm và da thiếu ẩm.',
    price: 245000,
    badge: 'Bán chạy',
    ingredients: ['Panthenol', 'Glycerin', 'Amino acid cleanser'],
    usage: 'Lấy lượng vừa đủ, massage trên da ướt rồi rửa sạch.',
    unit: 'Tuýp',
    manufacturer: 'Skin Lab Studio',
    countryOfOrigin: 'Hàn Quốc',
    form: 'Gel rửa mặt',
    specification: 'Tuýp 150ml',
    shelfLife: '24 tháng',
    ingredientHighlight: 'B5 và glycerin giúp làm sạch mà vẫn giữ độ ẩm tự nhiên.',
  },
  {
    slug: 'niacinamide-10-serum',
    name: 'Serum Niacinamide 10%',
    subCategory: 'Serum',
    benefit: 'Hỗ trợ sáng da và giảm dầu',
    description: 'Serum niacinamide nồng độ 10% hỗ trợ cân bằng dầu và cải thiện bề mặt da.',
    shortDescription: 'Tinh chất phù hợp da dầu, lỗ chân lông to và không đều màu.',
    price: 319000,
    badge: 'Nổi bật',
    ingredients: ['Niacinamide 10%', 'Zinc PCA'],
    usage: 'Thoa 2-3 giọt sau bước làm sạch và toner.',
    unit: 'Chai',
    manufacturer: 'Derma Focus',
    countryOfOrigin: 'Pháp',
    form: 'Tinh chất',
    specification: 'Chai 30ml',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Niacinamide 10% hỗ trợ đều màu da và kiểm soát bã nhờn.',
  },
  {
    slug: 'cica-repair-cream',
    name: 'Kem dưỡng Cica Repair',
    subCategory: 'Dưỡng ẩm',
    benefit: 'Phục hồi và làm dịu da',
    description: 'Kem dưỡng chứa cica, panthenol và squalane cho da nhạy cảm hoặc sau treatment.',
    shortDescription: 'Kem dưỡng cho da nhạy cảm cần phục hồi và khóa ẩm.',
    price: 355000,
    badge: 'Nổi bật',
    ingredients: ['Centella asiatica', 'Panthenol', 'Squalane'],
    usage: 'Thoa đều sau serum ở bước cuối routine.',
    unit: 'Hũ',
    manufacturer: 'Skin Lab Studio',
    countryOfOrigin: 'Nhật Bản',
    form: 'Kem',
    specification: 'Hũ 50g',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Cica, panthenol và squalane hỗ trợ làm dịu và khóa ẩm.',
  },
  {
    slug: 'acne-spot-gel',
    name: 'Gel chấm mụn Acne Spot',
    subCategory: 'Điều trị mụn',
    benefit: 'Hỗ trợ giảm mụn viêm tại chỗ',
    description: 'Gel chấm mụn chứa salicylic acid và tea tree cho vùng mụn cục bộ.',
    shortDescription: 'Gel chấm mụn tiện dùng cho routine chăm sóc da dầu mụn.',
    price: 185000,
    badge: 'Tiện dụng',
    ingredients: ['Salicylic acid', 'Tea tree oil', 'Niacinamide'],
    usage: 'Chấm trực tiếp lên nốt mụn 1-2 lần mỗi ngày.',
    unit: 'Tuýp',
    manufacturer: 'Acne Clinic',
    countryOfOrigin: 'Hàn Quốc',
    form: 'Gel',
    specification: 'Tuýp 15g',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Kết hợp Salicylic acid và tea tree cho vùng mụn cục bộ.',
  },
  {
    slug: 'uv-defense-spf50',
    name: 'Kem chống nắng UV Defense SPF50+',
    subCategory: 'Chống nắng',
    benefit: 'Bảo vệ da trước UVA/UVB',
    description: 'Kem chống nắng quang phổ rộng với kết cấu mỏng nhẹ, phù hợp dùng hằng ngày.',
    shortDescription: 'Chống nắng hằng ngày với kết cấu ráo mặt và dễ dùng dưới makeup.',
    price: 295000,
    badge: 'Bán chạy',
    ingredients: ['Uvinul A Plus', 'Uvinul T150', 'Vitamin E'],
    usage: 'Thoa lượng đủ lên da trước khi ra nắng 15 phút.',
    unit: 'Tuýp',
    manufacturer: 'Sunveil Derm',
    countryOfOrigin: 'Pháp',
    form: 'Kem',
    specification: 'Tuýp 50ml',
    shelfLife: '36 tháng',
    ingredientHighlight: 'Chống nắng phổ rộng SPF50+ PA++++.',
  },
  {
    slug: 'hyaluronic-plump-toner',
    name: 'Toner Hyaluronic Plump',
    subCategory: 'Làm sạch',
    benefit: 'Cấp ẩm tức thì sau rửa mặt',
    description: 'Toner chứa HA đa phân tử giúp da ẩm mượt và sẵn sàng cho các bước sau.',
    shortDescription: 'Bổ sung độ ẩm nhẹ cho da khô và da thiếu nước.',
    price: 265000,
    badge: 'Dễ dùng',
    ingredients: ['Hyaluronic acid', 'Betaine', 'Allantoin'],
    usage: 'Thấm ra bông hoặc vỗ trực tiếp lên da sau rửa mặt.',
    unit: 'Chai',
    manufacturer: 'Moist Barrier',
    countryOfOrigin: 'Nhật Bản',
    form: 'Dung dịch',
    specification: 'Chai 200ml',
    shelfLife: '24 tháng',
    ingredientHighlight: 'HA đa phân tử hỗ trợ giữ nước và làm mềm bề mặt da.',
  },
])

const deviceProducts = buildProducts('thiet-bi-y-te', [
  {
    slug: 'digital-thermometer-flex',
    name: 'Nhiệt kế điện tử đầu mềm Flex',
    subCategory: 'Nhiệt kế',
    benefit: 'Đo nhiệt độ nhanh và dễ đọc',
    description: 'Nhiệt kế điện tử đầu mềm với màn hình rõ nét, phù hợp theo dõi tại nhà.',
    shortDescription: 'Thiết bị cơ bản cho tủ thuốc gia đình và chăm sóc trẻ nhỏ.',
    price: 125000,
    badge: 'Thiết yếu',
    ingredients: ['Đầu đo mềm', 'Màn hình LCD'],
    usage: 'Bật thiết bị, đặt đúng vị trí đo và chờ tín hiệu hoàn tất.',
    unit: 'Cái',
    manufacturer: 'CareTech Medical',
    countryOfOrigin: 'Nhật Bản',
    form: 'Thiết bị đo',
    specification: 'Hộp 1 cái',
    shelfLife: '60 tháng',
    ingredientHighlight: 'Đầu đo mềm, thời gian đo nhanh trong vài chục giây.',
  },
  {
    slug: 'blood-pressure-home',
    name: 'Máy đo huyết áp Home',
    subCategory: 'Máy đo huyết áp',
    benefit: 'Theo dõi huyết áp tại nhà',
    description: 'Máy đo huyết áp bắp tay với màn hình lớn, thao tác một nút và lưu kết quả.',
    shortDescription: 'Thiết bị theo dõi huyết áp phù hợp cho gia đình và người lớn tuổi.',
    price: 890000,
    badge: 'Nổi bật',
    ingredients: ['Bộ nhớ lưu 60 kết quả', 'Màn hình LCD lớn'],
    usage: 'Quấn vòng bít đúng vị trí, ngồi thẳng và nhấn nút bắt đầu.',
    unit: 'Bộ',
    manufacturer: 'CareTech Medical',
    countryOfOrigin: 'Trung Quốc',
    form: 'Thiết bị điện tử',
    specification: 'Hộp 1 máy + vòng bít',
    shelfLife: '60 tháng',
    ingredientHighlight: 'Lưu bộ nhớ và hiển thị huyết áp, nhịp tim rõ ràng.',
  },
  {
    slug: 'mesh-nebulizer-air',
    name: 'Máy xông khí dung Mesh Air',
    subCategory: 'Máy xông',
    benefit: 'Hỗ trợ xông khí dung tại nhà',
    description: 'Máy xông khí dung dạng mesh nhỏ gọn, độ ồn thấp và dễ mang theo.',
    shortDescription: 'Giải pháp xông khí dung tiện lợi cho gia đình có trẻ nhỏ hoặc người lớn tuổi.',
    price: 1350000,
    badge: 'Cao cấp',
    ingredients: ['Công nghệ mesh', 'Cốc thuốc dung tích tiêu chuẩn'],
    usage: 'Cho dung dịch vào cốc, lắp mặt nạ và bật máy theo hướng dẫn.',
    unit: 'Bộ',
    manufacturer: 'MediAir',
    countryOfOrigin: 'Đức',
    form: 'Thiết bị điện tử',
    specification: 'Hộp 1 máy + phụ kiện',
    shelfLife: '48 tháng',
    ingredientHighlight: 'Công nghệ mesh cho hạt sương mịn, vận hành êm.',
  },
  {
    slug: 'glucose-monitor-smart',
    name: 'Máy đo đường huyết Smart',
    subCategory: 'Máy đo đường huyết',
    benefit: 'Đo đường huyết nhanh tại nhà',
    description: 'Máy đo đường huyết nhỏ gọn, thao tác nhanh với que thử riêng.',
    shortDescription: 'Thiết bị hỗ trợ kiểm tra đường huyết nhanh cho nhu cầu theo dõi tại nhà.',
    price: 740000,
    badge: 'Phổ biến',
    ingredients: ['Màn hình LCD', 'Bộ nhớ lưu kết quả'],
    usage: 'Lắp que thử, lấy mẫu máu đúng hướng dẫn và đọc kết quả trên màn hình.',
    unit: 'Bộ',
    manufacturer: 'GlucoCare',
    countryOfOrigin: 'Đài Loan',
    form: 'Thiết bị điện tử',
    specification: 'Hộp 1 máy + bút lấy máu',
    shelfLife: '60 tháng',
    ingredientHighlight: 'Đo nhanh, màn hình rõ, thao tác đơn giản tại nhà.',
  },
  {
    slug: 'pulse-oximeter-mini',
    name: 'Máy đo SpO2 Mini',
    subCategory: 'Thiết bị đo',
    benefit: 'Theo dõi SpO2 và nhịp tim',
    description: 'Máy đo nồng độ oxy đầu ngón tay với thiết kế nhỏ gọn, phù hợp theo dõi tại nhà.',
    shortDescription: 'Thiết bị theo dõi SpO2 và nhịp tim tiện lợi trong gia đình.',
    price: 420000,
    badge: 'Tiện lợi',
    ingredients: ['Màn hình OLED', 'Cảm biến đầu ngón tay'],
    usage: 'Kẹp vào đầu ngón tay, giữ yên vài giây để máy đọc kết quả.',
    unit: 'Cái',
    manufacturer: 'OxySafe',
    countryOfOrigin: 'Trung Quốc',
    form: 'Thiết bị đo',
    specification: 'Hộp 1 cái',
    shelfLife: '60 tháng',
    ingredientHighlight: 'Hiển thị cùng lúc SpO2 và nhịp tim trên màn hình OLED.',
  },
  {
    slug: 'medical-mask-4d',
    name: 'Khẩu trang y tế 4D',
    subCategory: 'Vật tư y tế',
    benefit: 'Bảo vệ hô hấp hằng ngày',
    description: 'Khẩu trang y tế 4D ôm sát mặt, chất liệu nhẹ và dễ thở.',
    shortDescription: 'Vật tư cơ bản cho nhu cầu di chuyển, làm việc và chăm sóc gia đình.',
    price: 78000,
    badge: 'Thiết yếu',
    ingredients: ['Vải không dệt nhiều lớp'],
    usage: 'Đeo che kín mũi miệng, thay mới sau thời gian sử dụng phù hợp.',
    unit: 'Hộp',
    manufacturer: 'SafeCare',
    countryOfOrigin: 'Việt Nam',
    form: 'Vật tư y tế',
    specification: 'Hộp 30 chiếc',
    shelfLife: '60 tháng',
    ingredientHighlight: 'Thiết kế 4D ôm mặt, dễ thở và phù hợp dùng hằng ngày.',
  },
])

const medicineProducts = buildProducts('thuoc', [
  {
    slug: 'paracetamol-500',
    name: 'Paracetamol 500mg',
    subCategory: 'Giảm đau hạ sốt',
    benefit: 'Hỗ trợ giảm đau, hạ sốt',
    description: 'Sản phẩm mock phục vụ trình diễn giao diện nhà thuốc online với thông tin đầy đủ.',
    shortDescription: 'Dữ liệu mô phỏng cho nhóm thuốc giảm đau hạ sốt.',
    price: 32000,
    badge: 'Phổ biến',
    ingredients: ['Paracetamol 500mg'],
    usage: 'Dùng theo hướng dẫn của dược sĩ hoặc bác sĩ.',
    unit: 'Hộp',
    manufacturer: 'PharmaCare',
    countryOfOrigin: 'Việt Nam',
    form: 'Viên nén',
    specification: 'Hộp 10 vỉ x 10 viên',
    shelfLife: '36 tháng',
    ingredientHighlight: 'Mỗi viên chứa Paracetamol 500mg.',
  },
  {
    slug: 'cough-syrup-honey',
    name: 'Siro ho Honey',
    subCategory: 'Ho cảm',
    benefit: 'Hỗ trợ làm dịu họng',
    description: 'Dữ liệu mock để mô phỏng danh mục thuốc với bố cục chi tiết, review và liên quan.',
    shortDescription: 'Sản phẩm mô phỏng cho nhóm siro ho và cảm.',
    price: 68000,
    badge: 'Mới',
    ingredients: ['Chiết xuất mật ong', 'Thảo dược làm dịu họng'],
    usage: 'Dùng theo hướng dẫn sử dụng trên bao bì.',
    unit: 'Chai',
    manufacturer: 'PharmaCare',
    countryOfOrigin: 'Việt Nam',
    form: 'Siro',
    specification: 'Chai 100ml',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Công thức siro dịu họng mô phỏng cho nhóm ho cảm.',
  },
  {
    slug: 'allergy-relief-10mg',
    name: 'Allergy Relief 10mg',
    subCategory: 'Dị ứng',
    benefit: 'Hỗ trợ giảm triệu chứng dị ứng',
    description: 'Dữ liệu mock dành cho thử nghiệm giao diện danh mục thuốc, không thay thế thông tin y khoa.',
    shortDescription: 'Mô phỏng một lựa chọn thuộc nhóm thuốc dị ứng.',
    price: 54000,
    badge: 'Tiện dụng',
    ingredients: ['Hoạt chất kháng histamine 10mg'],
    usage: 'Tham khảo hướng dẫn hoặc tư vấn chuyên môn trước khi dùng.',
    unit: 'Hộp',
    manufacturer: 'GlobalMed',
    countryOfOrigin: 'Ấn Độ',
    form: 'Viên nén',
    specification: 'Hộp 2 vỉ x 10 viên',
    shelfLife: '36 tháng',
    ingredientHighlight: 'Mỗi viên chứa hoạt chất kháng histamine 10mg.',
  },
  {
    slug: 'digestive-relief-sachet',
    name: 'Digestive Relief Sachet',
    subCategory: 'Tiêu hóa',
    benefit: 'Hỗ trợ giảm khó chịu tiêu hóa',
    description: 'Gói bột mô phỏng phục vụ trải nghiệm storefront cho danh mục thuốc tiêu hóa.',
    shortDescription: 'Dữ liệu mô phỏng cho nhóm thuốc hỗ trợ tiêu hóa.',
    price: 47000,
    badge: 'Phổ biến',
    ingredients: ['Công thức bột tiêu hóa'],
    usage: 'Dùng theo liều lượng ghi trên bao bì mô phỏng.',
    unit: 'Hộp',
    manufacturer: 'GlobalMed',
    countryOfOrigin: 'Việt Nam',
    form: 'Bột gói',
    specification: 'Hộp 20 gói',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Dạng bột gói tiện dùng cho nhóm tiêu hóa.',
  },
  {
    slug: 'saline-spray-care',
    name: 'Saline Spray Care',
    subCategory: 'Tai mũi họng',
    benefit: 'Làm sạch và hỗ trợ vệ sinh mũi',
    description: 'Xịt mũi nước muối mô phỏng cho nhóm chăm sóc tai mũi họng và sản phẩm OTC.',
    shortDescription: 'Mô phỏng sản phẩm xịt mũi thông dụng.',
    price: 39000,
    badge: 'Thiết yếu',
    ingredients: ['Dung dịch nước muối đẳng trương'],
    usage: 'Xịt hoặc nhỏ theo nhu cầu sử dụng.',
    unit: 'Chai',
    manufacturer: 'Ocean Pharma',
    countryOfOrigin: 'Pháp',
    form: 'Dung dịch xịt',
    specification: 'Chai 70ml',
    shelfLife: '36 tháng',
    ingredientHighlight: 'Dung dịch nước muối dùng cho chăm sóc mũi hằng ngày.',
  },
  {
    slug: 'antiseptic-cream-plus',
    name: 'Antiseptic Cream Plus',
    subCategory: 'Sát khuẩn ngoài da',
    benefit: 'Hỗ trợ chăm sóc vùng da trầy xước nhẹ',
    description: 'Kem bôi mock dùng để hoàn thiện danh mục thuốc và giao diện trang chi tiết.',
    shortDescription: 'Dữ liệu mô phỏng cho nhóm thuốc bôi ngoài da.',
    price: 59000,
    badge: 'Mới',
    ingredients: ['Hoạt chất sát khuẩn ngoài da'],
    usage: 'Bôi ngoài da theo hướng dẫn sử dụng.',
    unit: 'Tuýp',
    manufacturer: 'SkinMed Pharma',
    countryOfOrigin: 'Việt Nam',
    form: 'Kem bôi',
    specification: 'Tuýp 15g',
    shelfLife: '24 tháng',
    ingredientHighlight: 'Dạng kem bôi dùng ngoài da cho mục đích mock giao diện.',
  },
])

export const categoryNavItems = categoryNavItemSchema.array().parse(CATEGORY_CONFIG)
export const products = productSchema.array().parse([
  ...supplementProducts,
  ...skincareProducts,
  ...deviceProducts,
  ...medicineProducts,
])

export const commitments = [
  'Sản phẩm chính hãng, rõ nguồn gốc',
  'Tư vấn miễn phí theo nhu cầu sức khỏe',
  'Giao hàng toàn quốc trong 2-4 ngày',
]

export function formatPrice(price: number) {
  return new Intl.NumberFormat('vi-VN', {
    style: 'currency',
    currency: 'VND',
    maximumFractionDigits: 0,
  }).format(price)
}

export function getCategoryBySlug(slug: string) {
  return categoryNavItems.find((item) => item.slug === slug)
}

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug)
}

export function getRelatedProducts(product: Product, limit = 4) {
  return products
    .filter((item) => item.slug !== product.slug && item.topCategorySlug === product.topCategorySlug)
    .sort((left, right) => {
      const leftScore = left.subCategory === product.subCategory ? 0 : 1
      const rightScore = right.subCategory === product.subCategory ? 0 : 1

      if (leftScore !== rightScore) {
        return leftScore - rightScore
      }

      return right.rating - left.rating
    })
    .slice(0, limit)
}

export function getCategoryProducts(categorySlug: string) {
  return products.filter((product) => product.topCategorySlug === categorySlug)
}

export function listProducts(rawParams: Partial<Record<keyof ProductSearchParams, unknown>>) {
  const params = productSearchParamsSchema.parse(rawParams)
  const category = getCategoryBySlug(params.category ?? DEFAULT_CATEGORY_SLUG)

  if (!category) {
    return null
  }

  const categoryProducts = getCategoryProducts(category.slug)
  const filteredProducts = categoryProducts
    .filter((product) => {
      if (params.subCategory && params.subCategory !== 'Tất cả' && product.subCategory !== params.subCategory) {
        return false
      }

      if (params.priceRange === 'under-200') {
        return product.price < 200000
      }

      if (params.priceRange === '200-400') {
        return product.price >= 200000 && product.price <= 400000
      }

      if (params.priceRange === 'over-400') {
        return product.price > 400000
      }

      return true
    })
    .sort((left, right) => {
      switch (params.sort) {
        case 'price-asc':
          return left.price - right.price
        case 'price-desc':
          return right.price - left.price
        case 'name-asc':
          return left.name.localeCompare(right.name, 'vi')
        case 'rating-desc':
          return right.rating - left.rating
        default:
          return right.rating - left.rating
      }
    })

  const total = filteredProducts.length
  const totalPages = Math.max(1, Math.ceil(total / params.pageSize))
  const page = Math.min(params.page, totalPages)
  const startIndex = (page - 1) * params.pageSize
  const items = filteredProducts.slice(startIndex, startIndex + params.pageSize)

  return {
    category,
    filters: {
      subCategories: ['Tất cả', ...new Set(categoryProducts.map((product) => product.subCategory))],
    },
    items,
    pagination: {
      page,
      pageSize: params.pageSize ?? PRODUCTS_PER_PAGE,
      total,
      totalPages,
    },
    selected: {
      ...params,
      page,
    },
    suggestedProducts: categoryProducts
      .filter((product) => !items.some((item) => item.slug === product.slug))
      .sort((left, right) => right.rating - left.rating)
      .slice(0, 4),
  }
}
